### ISSUE TITLE
Chatroom connection Issue

### ISSUE THREAD

**Issue by LordYusei** [cellsheet/chlib#34]
Connected this up to my friends chatroom to test it's stability compared to ch.py, upon connecting I get the below error. Not sure if it's simple to fix or not but copied straight from the Python Idle Console.

  File "C:\Users\XXXXXX\Documents\chlib-master\chlib-master\chlib.py", line 476, in b
    group.pArray[bites[6]] = type("Post", (object,), {"group": group, "time": bites[1], "user": bites[2].lower() if bites[2] != '' else "#" + bites[3] if bites[3] != '' else "!anon" + Generate.aid(nColor, bites[4]) if nColor else "!anon" , "uid": bites[4], "unid": bites[5], "pnum": bites[6], "ip": bites[7], "post": re.sub("<(.*?)>", "", ":".join(bites[10:])).replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", "\"").replace("&apos;", "'").replace("&#39;", "'").replace("&amp;", "&"), "nColor": nColor, "fSize": fSize, "fFace": fFace, "fColor": fColor})
TypeError: aid() missing 1 required positional argument: 'uid'

**Comment by Hazerdous** [comment]
Oops, I can't believe this wasn't caught, sorry about that and thanks for the report. I just fixed it really quick.

You can re-download the chlib.py file and swap it out, or to fix your local copy, change the following lines:

[Line 50] `def aid(self, n, uid):` needs to be `def aid(n, uid):`
[Line 65] `def auth(self):` needs to be `def auth():`

**Comment by LordYusei** [comment]
No problem. I'll fix my local copy with your instructions but you're welcome. Seemed a bit strange to see the error but the library is definitely more stable than ch.py xD

**Comment by LordYusei** [comment]
Just spotted something else with your fix. If you run it with the example file you will notice it gives the error 
    self.pmAuth = Generate.auth(self)
TypeError: auth() takes 0 positional arguments but 1 was given

If you edit this: self.pmAuth = Generate.auth(self)
to self.pmAuth = Generate.auth()
Fixes it perfectly.

**Comment by Hazerdous** [comment]
Sorry about that, there was an error with my fix, the naming was a bit confusing.

If you return the `self` argument to both `Generate.auth()`s on lines 65 and 172 (make them the way they were before), it should fix this new issue.

I updated the main branch again to fix this, I changed the argument name so this confusion won't happen again. You can leave it as `self` on your copy, just know that in later versions, that argument will be `pm` instead. Functionality will remain the same however.

**Comment by piks** [comment]
If this issue was fixed please close this. I can not tell if its fixed or not from the comment history.

**Comment by LordYusei** [comment]
Yeah it's been fixed. No bugs as of now with the new version. Thanks for all the help.
