### ISSUE TITLE
Noticed a couple of things within main CHLIB calls

### ISSUE THREAD

**Issue by LordYusei** [cellsheet/chlib#36]
So, I was doing a bit of testing with the CHLIB calls when I found a couple of bugs I figured you should be aware of.

with the def recvparticipant script it calls the group as a string which stops you using functions like group.sendPost.

Also, within the group, there's no way to simultaneously send a message to all groups within the bot. So for example, if you wanted to post an announcement about new updates, you can't unless you go into each group and say it yourself. The same fault of recvparticipant stops you here.

The code I am trying for both is:

        def recvpartifipant(self, bit, group, user, uid):
            if bit == 1:
               print("User Joined The Chat: "+user)
               group.sendPost("Welcome "+user)
            else:
               print("User left the chat: "+user)
               group.sendPost("Goodbye "+user)

        if cmd == "announcement and len(args) > 0:
            msg = args
            for _group in groups:
               _group.sendPost("ANNOUNCEMENT: "+msg+ " <i>From "+user.lower(), True)

Just thought it was best to let you know. I haven't gone through chlib to see if I can do anything about this myself yet.

**Comment by james-d-elliott** [comment]
def recvpartifipant(self, bit, group, user, uid):

change it to:

def recvparticipant(self, bit, group, user, uid):

**Comment by LordYusei** [comment]
@james-d-elliott I get the same error for both. No matter what you do, it always gives a string error for both the functions you recommended. I'm not sure if it's something in the library causing it but upon looking into the library about 15 minutes ago, it doesn't seem to have a code for _group so I don't think that would fix it unless it was added. Here's the error for both btw

         recvparticipant
         group.sendPost("Goodbye "+user)
        AttributeError: 'str' object has no attribute 'sendPost'

It's the same on both

**Comment by james-d-elliott** [comment]
Ah I see the issue: self.call(bites[0], group, bit, user, uid)

Do: def recvparticipant(self, group, bit, user, uid):

**Comment by LordYusei** [comment]
@james-d-elliott Yeah that fixed that one. Thanks very much :) I can deal with not having announcements for now, I'll figure it out later. :P

**Comment by piks** [comment]
@LordYusei late post but, is it possible given your scenario to use the getGroup function located via self, `self.getGroup(*groupname*)` to obtain a group object?
Again, this is a really late reply but I am bored and I decided lets look at the uncertain if fixed issues.

**Comment by LordYusei** [comment]
No Problem at all Piks. The help is appreciated. I've been trying to figure this out for a while now with no luck. I shall try your idea now. If it works, you sir can have a beer on me as i've been stuck for a while with this. Lol

**Comment by LordYusei** [comment]
@piks No good either. I got this error with using self.groups and the group.name code. :
`TypeError: 'NoneType' object is not iterable`
I was using the code as below:
`if cmd == "ann" and len(args) > 0:
    group auth stuff here:
        for group in self.getGroup(group.name):
            group.sendPost("Announcement from "+user.lower()+": "+args)
    else: return`

**Comment by Hazerdous** [comment]
@LordYusei If this code is inside one of the recvCommand, recvPost, etc. functions. You can iterate over `self.cArray` to get the list of group objects. `self.groups` is the list of group names.

    if cmd == "ann" and len(args) > 0:
        # auth stuff here?
        text = "Announcement from "+user.lower()+": "+" ".join(args)
        for group in self.cArray:
            # can it post in this group?
            group.sendPost(text)

**Comment by LordYusei** [comment]
That works perfectly for what I wanted. Thanks very much bud. I suppose you could mark this as solved now. :)
