### ISSUE TITLE
Message background won't show?

### ISSUE THREAD

**Issue by LordYusei** [cellsheet/chlib#38]
Just gave the bot i'm coding a background and whenever I run it the background doesn't show. I logged into the bot and set the background manually but it still doesn't show. Any ideas?

**Comment by Hazerdous** [comment]
Are you using group.enableBg() ?

**Comment by LordYusei** [comment]
Closing. Seems it's only on the first or first few messages the background doesn't show up.

**Comment by LordYusei** [comment]
Sorry Just seen this when I closed it. I did try that yeah. Seems to be just on first few messages it doesn't show it
