### ISSUE TITLE
License conflict with TOS

### ISSUE THREAD

**Issue by asl97** [cellsheet/chlib#39]
License:
```to deal in the Software without restriction, including without limitation the rights to use```

TOS:
``` You may not use this library to explicitely run ANY code that was not created from the original user OR ported from any previous bot using the ch.py library (including any derivative) UNLESS you made any code that ran on ch.py FROM YOUR EXISTING KNOWLEDGE.```

**Comment by cellsheet** [comment]
https://github.com/cellsheet/chlib/commit/dc466f40db05b9186cfb6eb4310971cb376a1622
